# Rendering the server's two config files from Nix values.
#
# Deliberately a pure function of `lib` and nothing else — no `pkgs`, no
# derivation, no game content. That is what lets the same renderer serve both
# consumers: `services.zomboid` writes the result to the store, and the cluster
# repository renders it into a ConfigMap for the Helm chart. Both are exposed as
# `nixzoid.lib`.
#
# ## The two files
#
#   <name>.ini                  key=value, one per line. The server's own
#                               settings: ports, player cap, PVP, and the two
#                               mod keys.
#   <name>_SandboxVars.lua      a Lua table. The world's rules: zombie count,
#                               loot rarity, XP multipliers.
#
# Both live under `Server/` in the state directory, and both are named after
# `serverName` — which is why changing that name after first start looks like
# the server lost its settings.
{ lib }:
let
  # A newline in a value would end the line early and turn the rest into a key
  # the server does not recognise — which it reports, if at all, as a missing
  # setting rather than as a malformed file.
  noNewline =
    what: s:
    if lib.hasInfix "\n" s then
      throw "nixzoid: ${what} contains a newline, and the server config is strictly one key per line"
    else
      s;

  # The scalar spellings the server's own parser expects. Booleans are the only
  # surprise: it wants lowercase `true`/`false`, and `toString true` in Nix is
  # "1".
  iniScalar =
    key: v:
    if lib.isBool v then
      (if v then "true" else "false")
    else if lib.isInt v || lib.isFloat v then
      toString v
    else if lib.isString v then
      noNewline "the value of `${key}`" v
    else
      throw "nixzoid: `${key}` has type ${builtins.typeOf v}, which has no server-config spelling";

  iniValue =
    key: v:
    # Semicolons, for both `Mods` and `WorkshopItems` — the format the server
    # splits on. Rendering a Nix list here is the whole reason those are lists
    # in the module rather than a pre-joined string.
    if lib.isList v then lib.concatMapStringsSep ";" (iniScalar key) v else iniScalar key v;

  luaValue =
    indent: v:
    if lib.isBool v then
      (if v then "true" else "false")
    else if lib.isInt v || lib.isFloat v then
      toString v
    else if lib.isString v then
      ''"${lib.escape [ "\\" "\"" ] (lib.replaceStrings [ "\n" ] [ "\\n" ] v)}"''
    else if lib.isAttrs v then
      luaTable indent v
    else
      throw "nixzoid: sandbox values must be a boolean, a number, a string or a nested set, not ${builtins.typeOf v}";

  luaTable =
    indent: attrs:
    let
      inner = indent + "    ";
      entry = k: v: "${inner}${k} = ${luaValue inner v},";
    in
    "{\n" + lib.concatStringsSep "\n" (lib.mapAttrsToList entry attrs) + "\n${indent}}";
in
{
  # A `<name>.ini` fragment: only the keys given, in sorted order.
  #
  # Partial on purpose. The launcher merges this into whatever the server has
  # already written, key by key, so declaring `MaxPlayers` does not reset the
  # other ~150 options the server maintains for itself. `null` drops the key
  # entirely, which is how a setting is handed back to the server.
  mkServerIni =
    settings:
    let
      declared = lib.filterAttrs (_: v: v != null) settings;
    in
    ''
      # Generated by nixzoid. These keys are re-applied on every server start;
      # changing them in-game or by hand does not survive a restart.
    ''
    + lib.concatStringsSep "\n" (lib.mapAttrsToList (k: v: "${k}=${iniValue k v}") declared)
    + "\n";

  # A whole `<name>_SandboxVars.lua`.
  #
  # Whole, not merged, because merging would mean parsing Lua — and a
  # line-oriented approximation of that silently corrupts a nested group rather
  # than failing. Keys left undeclared take the server's own defaults, so a
  # small file is a complete one.
  mkSandboxVars = vars: ''
    -- Generated by nixzoid. Rewritten in full on every server start.
    SandboxVars = ${luaTable "" vars}
  '';
}
